# Generated by Django 5.2.13 on 2026-05-04 21:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location_type', models.CharField(choices=[('central', 'Almacén central'), ('pos', 'Tienda')], max_length=10)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_label', models.CharField(max_length=50)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=12)),
                ('reorder_point', models.PositiveIntegerField()),
                ('suggested_order_qty', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Iniciada'), ('pending', 'Pendiente'), ('partially_received', 'Parcialmente recibida'), ('closed', 'Cerrada')], db_index=True, default='pending', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('closing_justification', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='tienda.supplier')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('received_quantity_cumulative', models.PositiveIntegerField(default=0)),
                ('expected_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('partially_received', 'Parcialmente recibida'), ('complete', 'Completa')], default='pending', max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='tienda.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='tienda.purchaseorder')),
            ],
            options={
                'verbose_name': 'Línea de orden',
                'verbose_name_plural': 'Líneas de orden',
            },
        ),
        migrations.CreateModel(
            name='SalesDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cash_delivery', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_out_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_out_description', models.TextField(blank=True, default='')),
                ('cash_alert', models.CharField(blank=True, choices=[('ok', 'OK'), ('shortage', 'Faltante'), ('surplus', 'Sobrante')], max_length=10, null=True)),
                ('revenue_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_sales_days', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(limit_choices_to={'location_type': 'pos'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_days', to='tienda.location')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_sales_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jornada de venta',
                'verbose_name_plural': 'Jornadas de venta',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concept', models.CharField(choices=[('PURCHASE', 'Compra'), ('TRANSFER', 'Traslado'), ('SALE', 'Venta'), ('DAMAGE', 'Avería'), ('ADJUSTMENT', 'Ajuste')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paired_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inverse_pair', to='tienda.inventorymovement')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_movements', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='tienda.location')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='tienda.orderline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='tienda.product')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='tienda.purchaseorder')),
                ('sales_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='tienda.salesday')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DayCloseDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transferred_units', models.PositiveIntegerField()),
                ('final_count', models.PositiveIntegerField()),
                ('sold_units', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot_avg_cost_at_transfer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('central_stock_at_close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_close_details', to='tienda.product')),
                ('sales_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_close_details', to='tienda.salesday')),
            ],
            options={
                'verbose_name': 'Detalle de cierre de jornada',
                'verbose_name_plural': 'Detalles de cierre de jornada',
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.supplier')),
            ],
            options={
                'verbose_name': 'Asociación producto–proveedor',
                'verbose_name_plural': 'Asociaciones producto–proveedor',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', through='tienda.ProductSupplier', to='tienda.supplier'),
        ),
        migrations.CreateModel(
            name='LocationStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_stocks', to='tienda.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_stocks', to='tienda.product')),
            ],
            options={
                'verbose_name': 'Stock por ubicación',
                'verbose_name_plural': 'Stocks por ubicación',
                'constraints': [models.UniqueConstraint(fields=('product', 'location'), name='locationstock_unique'), models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='locationstock_quantity_gte_0')],
            },
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='orderline_unique_per_order'),
        ),
        migrations.AddConstraint(
            model_name='salesday',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('location',), name='salesday_unique_open_per_location'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'location'], name='mov_prod_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['sales_day'], name='mov_sales_day_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['concept', 'movement_type'], name='mov_concept_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='movement_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='movement_unit_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='dayclosedetail',
            constraint=models.UniqueConstraint(fields=('sales_day', 'product'), name='dayclosedetail_unique_per_salesday_product'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(fields=('product', 'supplier'), name='productsupplier_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='product_sale_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('avg_cost__gte', 0)), name='product_avg_cost_gte_0'),
        ),
    ]
