# Generated by Django 5.2.13 on 2026-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_seed_locations_and_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_label',
            field=models.CharField(choices=[('box', 'Caja'), ('pack', 'Paquete'), ('unit', 'Unidad')], max_length=10),
        ),
    ]
