# Generated by Django 5.2.13 on 2026-05-04 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_change_unit_label_to_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayclosedetail',
            name='central_stock_at_close',
            field=models.DecimalField(decimal_places=4, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dayclosedetail',
            name='snapshot_avg_cost_at_transfer',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['recorded_by'], name='mov_recorded_by_idx'),
        ),
        migrations.AddIndex(
            model_name='salesday',
            index=models.Index(fields=['seller'], name='salesday_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='salesday',
            index=models.Index(fields=['closed_by'], name='salesday_closed_by_idx'),
        ),
    ]
