# Generated by Django 5.2.13 on 2026-04-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_replace_with_django_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmodule',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_tienda', 'Puede acceder al módulo Tienda'), ('access_programador', 'Puede acceder al módulo Programador'), ('access_admin', 'Puede acceder al módulo Admin')]},
        ),
    ]
